server:
  port: 8090
spring:
  application:
    name: employee-service
#  datasource:
#    url: jdbc:mysql://localhost:3306/hibernateDemo?createDatabaseIfNotExist=true&useSSL=true
#    username: root
#    password: 1234
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    show-sql: true
#    generate-ddl: true
#    hibernate:
#      ddl-auto: create-drop
#      use-new-id-generator-mappings: false

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: false
  h2:
    console:
      enabled: true
      path: /h2
keycloak:
  auth-server-url: http://localhost:8088/auth
  realm: office-realm
  resource: emp-app
  principal-attribute: prefered_username
  enabled: true
  bearer-only: true
